[[redirects]]
  from = "/api/*"
  to = "/functions/server/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  included_files = ["./node_modules/@img/**/*"]
  directory = "/functions/server"

[build]
  functions = "build/server"
  command = "npm install && npm run build"
  publish = "build"

[[plugins]]
package = "netlify-plugin-inline-functions-env"
  [plugins.inputs]
  include = ["RS256KEY", "RS256KEYPUB"]