[build]
  functions = "build/server"
  command = "npm i && npm run build"
  publish = "build"

[functions]
  included_files=["node_modules/sharp/**/*"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200