[netlify]
  region = $ENV_DEFAULT_REGION
  aws_access_key_id = $ENV_ACCESS_KEY_ID
  aws_secret_access_key = $ENV_SECRET_ACCESS_KEY

[build]
  functions = "build/server"
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200