[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  functions = "build/server"
  command = "npm i && npm install --cpu=x64 --os=linux --libc=glibc sharp -f && npm install --cpu=x64 --os=linux --libc=musl sharp -f && npm run build"
  publish = "build"

[functions]
  external_node_modules = ["sharp"]
  included_files = ["node_modules/sharp/*"]