[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  included_files = ["./node_modules/@img/**/*"]

[build]
  functions = "build/server"
  command = "npm install && npm run build"
  publish = "build"